---
# tasks file for roles/win_ad_install

- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Setup Domain
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: update_result

- name: Reboot the machine
  win_reboot:
    shutdown_timeout: 3600
    reboot_timeout: 3600
  when: update_result.reboot_required
    
- name: List AD entries
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: output
- debug: var=output.stdout_lines

